version: '3.3'

services:
  php:
    build: $PWD/docker/nginx
    image: php-xdebug-ci
    volumes:
      - "$PWD/src:/var/www/html"
    depends_on:
      - db
    restart: always

  web:
    image: nginx:1.13.5-alpine
    volumes:
      - "$PWD/src:/var/www/html"
      - "$PWD/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - php

  db:
    image: mysql:5.7
    volumes:
      - "$PWD/docker/data/mysql:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laradb
      - MYSQL_USER=lara
      - MYSQL_PASSWORD=lara

  # mail:
  #   image: schickling/mailcatcher:latest
  #   ports:
  #     - "1080:1080"
  #   restart: always
